server:
 port: 9292
spring:
 h2:
  console:
   enabled: true
 appliction:
  name: PAYMENT-SERVICE

eureka:
 client:
  register-with-eureka: true
  fetch-registry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka/
 instance:
  hostname: localhost